app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    '''
    Class user that defines the user object that is sent to the database and password authentication on login
    '''
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    full_name = db.Column(db.String(255))
    email = db.Column(db.String(255))
    bio = db.Column(db.String(300))
    pass_secure = db.Column(db.String(255))

    comments = db.relationship('Comment', backref = 'user', lazy = "dynamic")
    pitches = db.relationship('Pitch', backref = 'user', lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))	 
   
    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    # @login_manager.user_loader
    # def load_user(user_id):
    #     return User.query.get(int(user_id))


    def __repr__(self):
        return f'User {self.username}'


class Pitch(db.Model):
    """docstring for Pitch class that defines the piches object. Getting pitches and single pitch"""
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String)
    content = db.Column(db.String(1000))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    comments = db.relationship('Comment', backref = 'pitch', lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,category):
        pitches = Pitch.query.filter_by(category = category).all()

        return pitches

    @classmethod
    def get_single_pitch(cls,id):
        single_pitch = Pitch.query.filter_by(id = id).first()

        return single_pitch

    @classmethod
    def count_pitches(cls,uname):
        user = User.query.filter_by(username = uname).first()
        pitches = Pitch.query.filter_by(user_id = user.id).all()

        pitches_count = 0
        for pitch in pitches:
            pitches_count += 1

        return pitches_count

class Comment(db.Model):
    """docstring for Comment. this defines the comment object and getting the comments based on the pitch id"""

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch_id):
        comments = Comment.query.filter_by(pitch_id = pitch_id).all()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required 

class PitchForm(FlaskForm):
    '''
    Defines pitch column names and their data values
    '''
    title =StringField('Pitch title',validators =[Required()])
    text =TextAreaField('Text',validators=[Required()])
    cartegory= SelectField('Type',choices=[('pickup_pitches','Pickup-line pitches'),('interview','Interview pitch','product''Product pitch'),('promotion','Promotion pitch')],validators =[Required()])
    submit=SubmitField('Submit')
    
class UpdateProfile(FlaskForm):
    '''
    Class that updates user profile
    '''
    bio =TextAreaField('Bio',validators=[Required()])
    submit =SubmitField('Submit')
    
class CommentForm(FlaskForm):
    '''
    Defines columns for the comment form section
    '''
    text =TextAreaField('Leave a comment:',validators =[Required()])
    submit =SubmitField('Submit')

app/__init__.py
from flask import Flask 
from flask_bootstrap import Bootstrap 
from flask_sqlalchemy import SQLAlchemy 
from flask_mail import Mail
from flask_login import LoginManager
from flask_simplemde import SimpleMDE 

boostrap =Bootstrap()
db =SQLAlchemy()
mail=Mail

login_manager =LoginManger()
login_manager.session_protrction ='strong'
login_manager.login_view ='auth.login'

simple =SimpleMDE()

def create_app(config_name):
    app= Flask(__name__)
    app.config.from_object(config_options[config_name])
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    from .main import main as main_bluperint
    app.register_blueprint(main_blueprint)
    
    from.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')
    
    return app

app/main/__init__.py
from flask import Blueprint

main =Blueprint('main',__name__)
from .import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from .import main
from flask_login import login_required,current_user 
import datetime  
from ..models import User,Pitch,Comment  
from .. import db 
from .forms import UpdateProfile,PitchForm,CommentForm 

@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data 
    '''
    title ="Pitch perfect"
    
    pickup_pitches =Pitch.get_pitches("pickup-pitches")
    interview_pitches =Pitch.get_pitches("interview")
    product_pitches =Pitch.get_pitches("product")
    promotion_pitches=Pitches.get_pitches("promotion")
    
    return render_template('index.html',title =title,pickup=pickup_pitches,interview=interview_pitches,product=product_pitches,promotion=promotion_pitches)

@main.route('/user/<uname>')
def profile(uname):
    user =User.query,filter_by(username=uname).first()
    
    if user is None:
        abort(404)
        
        form =UpdateProfile()
        
        if form.validate_on_submit():
            user.bio =form.bio.data
            
            db.session.add(user)
            db.session.commit()
            
            return redirect(url_for('profile/update.html',form=form))
        
@main.route('/pitch/new',methods =['GET','POST'])
@login_required
def new_pitches():
    pitch_form =PitchForm()
    if pitch_form.validate_on_submit():
        title =pitch_form.title.data
        pitch =pitch_form.txt.datacategory = pitch_form.cartegory.data
        
        new_pitch =Pitch(title =tile,content =pitch,category=category,user=current_user,lokes=0,dislikes=0)
        
        new_pitch.save_pitch()
        return redirect(url_for('.index'))
    
    title ='New Pitch'
    return render_template('new_pitch.html',title=title,pitch_form=pitch_form)

@main.route('/pitches/pickup_pitches')
def pickup_pitches():
    pitches =Pitch.get_pitches('pickup_pitches')
    
    return render_template("pickup_line.html",pitches=pitches)
    
@main.route('/pitches/interview_pitches')
def interview_pitches():
    pitches=Pitch.get_pitches('interview')
    
    return render_template("interview_piches.html",pitches=pitches)

@main.route('/pitches/product_pitches')
def product_pitches():
    pitches =Pitch.get_pitches('product')
    
    return render_template('product_pitches.html',pitches=pitches)

@main.route('/pitches/promotion_pitches')
def promotion_pitches():
    pitches =Pitch.get_pitches('promotion')
    
    return render_template('promotion_pitches.html',pitches =pitches)

@main.route('/pitch/<int:id>',methods=['GET','POST'])
def pitch(id):
    pitch =Pitch.get_single_pitch(id)
    posted_date=pitche.posted.strftime'(%b %d,%Y')
    if request.args.get("like"):
        pitch.dislike =pitch..dislikes +1
        db.session.add(pitch)
        db.session.commit()
        
        return redirect("/pitches/{pitch_id}".format(pitch_id = pitch.id))
    
    comment_form.validate_on_submit():
        comment =comment_form.text.data
        
        new_comment=Comment(comment =comment,user_id =current_user,pitch_id=pitch)
        new_comment.save_comment()
        
        comments =Comments.get_comments(pitch)
        return.render_template('pitch.html', pitch=pitch,comment_form =comment_form,comments=comments,date=posted_date)
    
@main.route('/user/<uname>pitches')
def user_pitches(uname):
    user =User.query.filter_by(username=uname).first()
    pitches =Pitch.query.filter_by(user_id =user.id).all()
    pitches_count =Pitch.count_pitches(uname)
    
    return render_template("profile/pitches.html",user=user,pitches=pitches,pitches_count=pitches_count)    

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{%block navbar%}
    {%include 'navbar.html'%}
{%endblock%}

{%block styles%}
    {{super()}}
    <link href="https://fonts.googleapis.com/css?family=Ranga&display=swap" rel="stylesheet">
{%endblock%}

app/templates/four-four.html
{% extends 'base.html' %}
{% block content%}
	<div class="container">
		<div class="jumbotron text-center">
			<h2> Ooooops!! This page does not exist.</h2>
			<p>Home</p><a href="/" class="btn btn-success">Home</a>
		</div>
	</div>
{% endblock %}

app/templates/index.html
{%extends 'base.html'%}
{%import 'macros.html' as macro%}

{%block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ranga" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cormorant" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {%endblock%}

    {%block content%}
    <div class="jumbotron text-center" style="background-color:#34e6b8; color:#000000; padding:100px 25px; font-family:'Monoton',cursive;">
        <h1>Pitch Perfect</h1>
    </div>
    <div class="container" style="padding-bottom:20px;">
    <a href="{{url_for('main.new_pitch')}}" class="btn btn-success">Create pitch</a>
    </div>

    <div class="container" style="font-family:'Cormorant Upright',serif;">
        <div class="row">
            <div class="col-md-3">
                <div class="col-md-3">
                    <div class="well well-lg">
                        <h3>Pickup line pitches</h3>
                        <p>Wanna impress someone?Shoot your shot!</p>
                        <a href="{{url_for('main.pickup_pitches')}}" class="btn btn-primary -center">View</a>
                    </div>
                    <div class="well well-lg">
                        <h3>Interview pitches</h3>
                        <p>Ace an interview?Look no further!</p>
                        <a href="{{url_for('main.interview_pitches')}}" class="btn btn-primary -center">View</a>
                    </div>

                    <div class="well well-lg">
                        <h3>Product pitches</h3>
                        <p>Here's the right place to showcase your products</p>
                        <a href="{{url_for('main.product_pitches')}}" class="btn btn-primary -center">View</a>
                    </div>
                    <div class="well well-lg">
                        <h3>Promotion pitches</h3>
                        <p>To promote anything,Step up right away and begin</p>
                        <a href="{{url_for('main.promotion_pitches')}}" class="btn btn-primary -center">View</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
                    
              

app/templates/interview_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="background-color: #E63462; color: #fff; padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Interview Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/macros.html
{% macro displayPitches(pitches_list)%}
    {%for pitch in pitches_list%}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
            <div class="well well-lg">
                <h4>{{pitch.title}}</h4>
                <p>{{pitch.content|truncate(100)}}</p>
                <p>Written by:{{pitch.user.username}}  <a href="/pitch/{{pitch.id}}" class="btn btn-primary pull-right">Read</a></p>
               
            </div>
        </div>
        {%endfor%}
    {%endmacro%}

{%macro displayComments(comments_list)%}
        {%for coments in comments_list%}
            <div class="col-md-12">
                <h5>{{comment.user.username}}</h5>
                <p>{{comment.comment}}</p>
                
            </div>
        {%endfor%}
    {%endmacro%}

app/templates/navbar.html
<div class="navbar navbar-light" role="navigation" style="margin-bottom:0; border-bottom:1px solid;">
    <div class="container-fluid">
        <div navbar-header>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Pitch Perfect</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.pickup_pitches)}}'">Pickup lines</a></li>
                <li><a href="{{url_for('main.interview_pitches)}}'">Interview Pitches</a></li>
                <li><a href="{{url_for('main.product_pitches)}}'">Product Pitches</a></li>
                <li><a href="{{url_for('main.promotion_pitches)}}'">Promotion Pitches</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {%if current_user.is authenticated%}
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdwon" role="button" aria-haspopup="true" aria-expanded="false">{{currenr_user.username|capitalize}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ur_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('main.user_pitches',uname=current_user.username)}}">My Pitches</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{url_for('auth.logout')">Sign out</a></li>
                    </ul>
                </li>   
                        {%else%}
                        <li><a href="{{url_for('auth.logout')}}">Sign in</a></li>
                        <li><a href="{{url_for('auth.register')}}'">Sign up</a></li>

                    
            </ul>
            {%endif%}
        </div>
    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h3>Create a pitch</h3>
            <hr>
            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>

{% endblock %}

app/templates/pickup_line.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="background-color: #E63462; color: #fff; padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Pickup Line Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{%endblock%}
<!-- Content block -->
{%block content%}
<div class="container" style="font-family: 'Indie Flower', cursive;">
    <div class="row">
        <h3>{{pitch.title}}</h3>
        <hr>
        <p>{{pitch.content}}</p>
        <span>
          <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>
          <a href="/pitch/{{pitch.id}}?like=1">
              <i class="far fa-thumbs-up"></i>
          </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">
              <i class="far fa-thumbs-down"></i>
          </a>{{pitch.dislikes}}
        </span>

    </div>
    <div class="row">
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>

</div>
{%endblock%}

app/templates/product_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="background-color: #E63462; color: #fff; padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Product Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/profile/pitches.html
{% extends 'base.html'%}
{%import 'macros.html' as macro%}

{%block content%}
<div class="container">
    <div class="row">
        <h3>{{user.username|capitalize}}</h3>
        <hr>
        <div class="col-md-9">
            <p>Name:{{user.full_name}}</p>
            <p>No of pitches:{{pitches_count}}</p>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>Pitches</h3>
                <hr>
                {{macro.displayPitches(pitches)}}
            </div>
        </div>
    </div>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content%}
<div class="container">
    <div class="row">
        <h3>{{user.username|capitaliaze}}</h3>
        <hr>
        <div class="col-md-9">
            <p>Name:{{user.firstname}} {{user.lastname}}</p>
            <p>No of pitches:{{pitches}}</p>
        </div>
    </div>
    <div class="row">
        <div class="co-md-12">
            <h3>Bio</h3>
            {% if user.bio%}
                <p></p>
            {%else%}
                <p>{{user.username|capitalize}} has no bio</p>
            {%end if%}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% end if %}
        </div>
    </div>
</div>
{%end block%}

app/templates/profile/update.html
{%extends 'base.html' %}
{% import 'boostrap/wtf.html' as wtf %}

{5block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{%endblock%}

app/templates/promotion_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="background-color: #E63462; color: #fff; padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Promotion Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}